// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizzApp.Api.Models;

namespace QuizzApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201012181438_IntialCreate")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuizApp.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AnswerDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("AnswerId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            AnswerDate = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 2,
                            QuizId = 4
                        },
                        new
                        {
                            AnswerId = 3,
                            AnswerDate = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 1,
                            QuizId = 2
                        },
                        new
                        {
                            AnswerId = 4,
                            AnswerDate = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 3,
                            QuizId = 3
                        },
                        new
                        {
                            AnswerId = 2,
                            AnswerDate = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 3,
                            QuizId = 1
                        });
                });

            modelBuilder.Entity("QuizApp.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DepName = "Developing",
                            EmployeeId = 1
                        },
                        new
                        {
                            DeptId = 2,
                            DepName = "Support",
                            EmployeeId = 2
                        },
                        new
                        {
                            DeptId = 3,
                            DepName = "HR",
                            EmployeeId = 3
                        },
                        new
                        {
                            DeptId = 4,
                            DepName = "Economy",
                            EmployeeId = 4
                        });
                });

            modelBuilder.Entity("QuizApp.Models.Employe", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Admin = false,
                            DepartmentId = 1,
                            Email = "ana@hot.com",
                            FirstName = "Anas",
                            LastName = "Alhu",
                            PhotoPath = "Images / test.test.png"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Admin = true,
                            DepartmentId = 2,
                            Email = "Mike@hot.com",
                            FirstName = "Mike",
                            LastName = "Mike",
                            PhotoPath = "Images / test.test.png"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Admin = false,
                            DepartmentId = 1,
                            Email = "viktor@hot.com",
                            FirstName = "Viktor",
                            LastName = "Viktor",
                            PhotoPath = "Images / test.test.png"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Admin = true,
                            DepartmentId = 3,
                            Email = "andrs@hot.com",
                            FirstName = "Anders",
                            LastName = "Anderson",
                            PhotoPath = "Images / test.test.png"
                        });
                });

            modelBuilder.Entity("QuizApp.Models.Quiz", b =>
                {
                    b.Property<int>("QizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QizId");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            QizId = 1,
                            AnswerId = 2,
                            Description = "To Ask",
                            QuizType = 3,
                            Title = " How are you ?"
                        },
                        new
                        {
                            QizId = 2,
                            AnswerId = 3,
                            Description = "Somthing",
                            QuizType = 7,
                            Title = " What you will do today ?"
                        },
                        new
                        {
                            QizId = 3,
                            AnswerId = 4,
                            Description = "To Ask",
                            QuizType = 5,
                            Title = " Which day is your birthday ?"
                        },
                        new
                        {
                            QizId = 4,
                            AnswerId = 1,
                            Description = "To Ask",
                            QuizType = 1,
                            Title = "How are you ?"
                        });
                });

            modelBuilder.Entity("QuizApp.Models.QuizEmployeeList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuizEmployeeLists");
                });

            modelBuilder.Entity("QuizApp.Models.Record", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("RecordId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            RecordId = 1,
                            AnswerId = 2,
                            EmployeId = 3,
                            QuizId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
